### ISSUE TITLE
Pre-cache Terraform providers

### ISSUE THREAD

**Issue by aries1980** [opsgang/alpine_build_scripts#1]
Since 0.10.x, providers are not shipped with Terraform Core, but as a separate binary that you need to download for every(?) module.

To speed this up, my proposal is to
- Cache the binaries into /usr/local/lib/terraform/
- Create a /root/.terraformrc with the providers, like
```
providers {
  aws = /usr/local/lib/terraform/terraform-provider-softlayer"
}
```
- Add the provider version numbers to the Docker image label list. (Probably a separate ticket for each Docker image?)

**Comment by leventyalcin** [comment]
@aries1980 Have you tried to work different versions of providers with this way?

What happens if the cached version of the provider 0.0.1 and the version constraint is set to `~> 1.0.0`?

**Comment by aries1980** [comment]
@leventyalcin : I haven't tried, but I expect TF to download the version that satisfies the criteria.
If this is not a viable option, the user still can replace the provider with a mounted volume. My proposal is rather to ship the image with the latest stable providers.

**Comment by jinal--shah** [comment]
https://github.com/opsgang/docker_aws_terraform/commit/d3142da8202794922bff14a37ced8825efd5e39a fixes this.

It honours the terraform plugin cache dir options for terraform >=0.10.7 , and basically treats the preinstalled plugins dir as this cache dir for anything > 0.10.0  - for versions >0.10.0 but <0.10.7, the docker entrypoint mimics what the new options do.

Alternatively you can mount a host volume instead to /tf_plugins_cache_dir, and pass `-e TF_PLUGIN_CACHE_DIR=/tf_plugins_cache_dir` to `docker run`. (Or mount your own $HOME/.terraformrc on the container specifying plugin_cache_dir location).
